### ISSUE TITLE
Plots should accept list of ticks

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#172]
The x/y/zticker plot options currently only support a number, but wanting to supply an explicit list of tick positions and labels is very common and should be easily supported. Therefore we should accept a list of tuples of the form ``[(value, label), ...]`` to specify ticks explicitly.

**Comment by philippjfr** [comment]
Since bd1378b9d46fe65856779263ed617995d0a038a4 ElementPlots accept an explicit list of x/y/zticks which may either contain tuples of the position and corresponding label or just the positions. The issue can therefore be closed.

**Comment by basnijholt** [comment]
May I still suggest ```xticks=0``` for if you don't want to hide the labels as well.

**Comment by philippjfr** [comment]
Done.

**Comment by basnijholt** [comment]
``xticks=0`` works fine, but you forgot to check ``yticks``.

**Comment by philippjfr** [comment]
Thanks, fixed.
