### ISSUE TITLE
Tap stream doesn't work with bokeh serve deployment

### ISSUE THREAD

**Issue by kpalin** [ioam/holoviews#2231]
Have tried, and failed, to get Tap stream working on standalone holoviews/bokeh app.  Tried to port the [Tap example](https://github.com/ioam/holoviews/blob/master/examples/reference/streams/bokeh/Tap.ipynb) to bokeh serve deployed version but that doesn't work either. It seems that the tap events are not coming back to python side. 

Below is the code that doesn't respond to clicks but shows the initial plot just fine.  Without the last two lines, the code works fine on jupyter notebook. As a side note: datashader works fine, so some events get through to the server.

```
import pandas as pd
import numpy as np
import holoviews as hv
from holoviews import streams
hv.extension('bokeh', width=90)

hv.opts(
    "HeatMap [width=700 height=500 logz=True fontsize={'xticks': '6pt'}, tools=['hover'] xrotation=90] (cmap='RdBu_r')"
)
hv.opts(
    "Curve [width=375 height=500 yaxis='right'] (line_color='pink') {+framewise}"
)
# Declare dataset
df = pd.read_csv(
    'http://assets.holoviews.org/data/diseases.csv.gz', compression='gzip')
dataset = hv.Dataset(df, vdims=('measles', 'Measles Incidence'))

# Declare HeatMap
heatmap = hv.HeatMap(
    dataset.aggregate(['Year', 'State'], np.mean),
    label='Measles Incidence').select(Year=(1928, 2002))

# Declare Tap stream with heatmap as source and initial values
posxy = hv.streams.Tap(source=heatmap, x=1951, y='New York')


# Define function to compute histogram based on tap location
def tap_histogram(x, y):
    return hv.Curve(
        dataset.select(State=y, Year=int(x)),
        kdims='Week',
        label='Year: %s, State: %s' % (x, y))


hmap = heatmap + hv.DynamicMap(tap_histogram, kdims=[], streams=[posxy])

doc = hv.renderer('bokeh').server_doc(hmap)
doc.title = 'HoloViews Bokeh App'
```

**Comment by jlstevens** [comment]
Thanks for reporting this. Definitely something to address before the next release.

**Comment by philippjfr** [comment]
This turned out to be a very annoying one line bug, which I've now fixed in the PR referenced above.

**Comment by ahuang11** [comment]
Hi, I tried `bokeh serve file.py` with kpalin's code
```python
import pandas as pd
import numpy as np
import holoviews as hv
from holoviews import streams
hv.extension('bokeh', width=90)

hv.opts(
    "HeatMap [width=700 height=500 logz=True fontsize={'xticks': '6pt'}, tools=['hover'] xrotation=90] (cmap='RdBu_r')"
)
hv.opts(
    "Curve [width=375 height=500 yaxis='right'] (line_color='pink') {+framewise}"
)
# Declare dataset
df = pd.read_csv(
    'http://assets.holoviews.org/data/diseases.csv.gz', compression='gzip')
dataset = hv.Dataset(df, vdims=('measles', 'Measles Incidence'))

# Declare HeatMap
heatmap = hv.HeatMap(
    dataset.aggregate(['Year', 'State'], np.mean),
    label='Measles Incidence').select(Year=(1928, 2002))

# Declare Tap stream with heatmap as source and initial values
posxy = hv.streams.Tap(source=heatmap, x=1951, y='New York')


# Define function to compute histogram based on tap location
def tap_histogram(x, y):
    return hv.Curve(
        dataset.select(State=y, Year=int(x)),
        kdims='Week',
        label='Year: %s, State: %s' % (x, y))


hmap = heatmap + hv.DynamicMap(tap_histogram, kdims=[], streams=[posxy])

doc = hv.renderer('bokeh').server_doc(hmap)
doc.title = 'HoloViews Bokeh App'
```
and I still experience the same issue as kpalin using the latest versions:
holoviews==1.9.2
bokeh==0.12.13

**Comment by philippjfr** [comment]
Yes, it's still not released. v1.9.3 is long overdue! We'll aim to release by Monday.
