### ISSUE TITLE
Datashader images missing when there is a datetime axis

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#2299]
holoviews/examples/user_guide/14-Large_Data.ipynb is missing the actual plots for the timeseries that have a datetime x axis:

![image](https://user-images.githubusercontent.com/1695496/35762706-2e806ed0-0861-11e8-8d5e-d9beea3d4bc5.png)

**Comment by jlstevens** [comment]
I've been plotting a lot of stuff with datashader that has a datetime axis though I've mostly been using ``regrid``. Wonder what is going on here...

**Comment by philippjfr** [comment]
Introduced this issue in a recent PR, I've fixed it in the PR above and added a unit test to avoid future regressions.

**Comment by jlstevens** [comment]
I'm about to merge that PR so I'll close this issue now.

**Comment by sfrodrigues** [comment]
Hey guys,

the issue seems to not be completely solved. I still dont have any data points when I'm using datashader and a timestamp for the x axis. The initial plot appears but as soon as you interact with it, everything vanishes. 

The bug is also present in 1.9.3 but it works fine in 1.9.1.

**Comment by jbednar** [comment]
@jlstevens, that sounds like the same issue I had a few days ago that you and Chris were unable to reproduce.

**Comment by philippjfr** [comment]
I can reproduce it.

**Comment by jbednar** [comment]
Whew.  Once Philipp can reproduce it, it's as good as solved. :-)

**Comment by philippjfr** [comment]
Fix was merged and released in 1.9.4.
