### ISSUE TITLE
holoviews (fresh) jupyterlab extension problem

### ISSUE THREAD

**Issue by stonebig** [ioam/holoviews#2379]
not sure if it's me or holoviews:
- this type of example doesn't seem work (yet) in Jupyterlab:
````
# Holoviews
# for more example, see http://holoviews.org/Tutorials/index.html
import numpy as np
import holoviews as hv
hv.extension('matplotlib')
dots = np.linspace(-0.45, 0.45, 11)
fractal = hv.Image(image)

layouts = {y: (fractal * hv.Points(fractal.sample([(i,y) for i in dots])) +
               fractal.sample(y=y) )
            for y in np.linspace(0, 0.45,11)}

hv.HoloMap(layouts, kdims=['Y']).collate().cols(2)
````

giving:
![holoju01](https://user-images.githubusercontent.com/4312421/36755004-0ef2528c-1c0b-11e8-90ca-7ac4ab46c64f.PNG)

but the ultra-tricky one ... does ???

![holoju02](https://user-images.githubusercontent.com/4312421/36755077-4ffcda4a-1c0b-11e8-91ef-e42a4bf9b112.PNG)

**Comment by philippjfr** [comment]
Seems to work for me:

<img width="1285" alt="screen shot 2018-02-27 at 10 04 30 pm" src="https://user-images.githubusercontent.com/1550771/36757740-421b5cd6-1c0a-11e8-9604-5b6d1c8aeab0.png">

Do you see any errors on your console?

**Comment by stonebig** [comment]
as usual, node-gyp failed to provide service to me, so I may have a missing nut or bolt, looking in the console...

**Comment by stonebig** [comment]
````
widgets.js:57 Uncaught TypeError: y.slider is not a function
    at Object.o [as init_slider] (widgets.js:57)
    at <anonymous>:25:11
    at t.attachWidget (panellayout.js:210)
    at t.insertWidget (panellayout.js:113)
    at t._insertOutput (widget.js:331)
    at t.onModelChanged (widget.js:242)
    at m (index.js:475)
    at Object.l [as emit] (index.js:433)
    at e.emit (index.js:106)
    at e._onListChanged (model.js:294)
````

**Comment by stonebig** [comment]
but this error seems also to happen before holoviews cell execution. so I don't have  specific message, maybe a general problem

**Comment by stonebig** [comment]
but still, I apparently have holoviews extension:
````
jupyter labextension list

JupyterLab v0.31.8
Known labextensions:
   app dir: C:\WinPython\bd36\buildQt5\winpython-64bit-3.6.x.0\python-3.6.4.amd64\share\jupyter\lab
@jupyter-widgets/jupyterlab-manager
        @jupyter-widgets/jupyterlab-manager v0.33.2 enabled  ok
@jupyterlab/vega3-extension
        @jupyterlab/vega3-extension v0.14.2 enabled  ok
@pyviz/jupyterlab_holoviews
        @pyviz/jupyterlab_holoviews v0.1.0 enabled  ok
bqplot
        bqplot v0.3.6 enabled  ok
jupyter-leaflet
        jupyter-leaflet v0.7.1 enabled  ok
jupyter-matplotlib
        jupyter-matplotlib v0.3.0 enabled  ok
jupyter-threejs
        jupyter-threejs v0.4.1 enabled  ok
jupyterlab_bokeh
        jupyterlab_bokeh v0.3.1 enabled  ok
````

**Comment by stonebig** [comment]
maybe a 3rd impartial user may help to determine which pc is not "normal". I suppose it's mine by default.

**Comment by stonebig** [comment]
same issue with the holoviews galery dragon_curve example....

**Comment by philippjfr** [comment]
Thanks that's helpful, the error makes it seem like jQueryUI isn't being loaded, I'll look into it.

**Comment by jlstevens** [comment]
Seems to work for me:

![image](https://user-images.githubusercontent.com/890576/36788950-cb0e2136-1c87-11e8-83fd-4b9cec43f2e3.png)

That said there may be some non-deterministic issue and I just got lucky.

**Comment by philippjfr** [comment]
There should be no async or non-deterministic issues since jQuery and jQueryUI should be shipped in the JupyterLab webpack bundle. Maybe a browser difference? I've only tried Chrome so far.

**Comment by philippjfr** [comment]
I've made a small change in the extension which might fix this, might be worth trying an update.

**Comment by stonebig** [comment]
Trying with @pyviz/jupyterlab_holoviews v0.2.0 ... no change.

Well, it's nevertheless a 50% success, on a jupyterlab beta1 only stack. with classic notebook still working.

History of jupyterlab install messages:
````

C:\WinPython\bd36\buildQt5\winpython-32bit-3.6.x.0\scripts>jupyter labextension install @pyviz/jupyterlab_holoviews
> C:\WinPython\bd36\buildQt5\winpython-32bit-3.6.x.0\python-3.6.4\..\tools\n\npm.CMD pack @pyviz/jupyterlab_holoviews
pyviz-jupyterlab_holoviews-0.2.0.tgz
> node C:\WinPython\bd36\buildQt5\winpython-32bit-3.6.x.0\python-3.6.4\lib\site-packages\jupyterlab\staging\yarn.js install
yarn install v1.3.2
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has unmet peer dependency "react@^15.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has unmet peer dependency "react-dom@^15.0.0".
warning "@jupyterlab/json-extension > react-highlighter@0.4.2" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/vdom-extension > @nteract/transform-vdom@1.1.1" has unmet peer dependency "react@^15.6.1".
warning "jupyter-leaflet > leaflet.markercluster@1.3.0" has incorrect peer dependency "leaflet@~1.0.3".
[4/4] Building fresh packages...
[-/4] ⡀ waiting...
[2/4] ⡀ canvas: C:\WinPython\bd36\buildQt5\winpython-32bit-3.6.x.0\pyth
[3/4] ⡀ jupyter-matplotlib
[4/4] ⡀ canvas-prebuilt: 404 status code downloading tarball https://gi
warning Error running install script for optional dependency: "C:\\WinPython\\bd36\\buildQt5\\winpython-32bit-3.6.x.0\\python-3.6.4\\share\\jupyter\\lab\\staging\\node_modules\\canvas-prebuilt: Command failed.\nExit code: 1\nCommand: node_modules\\.bin\\node-pre-gyp install\nArguments: \nDirectory: C:\\WinPython\\bd36\\buildQt5\\winpython-32bit-3.6.x.0\\python-3.6.4\\share\\jupyter\\lab\\staging\\node_modules\\canvas-prebuilt\nOutput:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@6.11.5 | win32 | ia32
node-pre-gyp info check checked for \"C:\\WinPython\\bd36\\buildQt5\\winpython-32bit-3.6.x.0\\python-3.6.4\\share\\jupyter\\lab\\staging\\node_modules\\canvas-prebuilt\\canvas\\build\\Release\\canvas-prebuilt.node\" (not found)
node-pre-gyp http GET https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.0/canvas-prebuilt-v1.6.0-node-v48-win32-ia32.tar.gz
node-pre-gyp http 404 https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.0/canvas-prebuilt-v1.6.0-node-v48-win32-ia32.tar.gz
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.0/canvas-prebuilt-v1.6.0-node-v48-win32-ia32.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (C:\\WinPython\\bd36\\buildQt5\\winpython-32bit-3.6.x.0\\python-3.6.4\\share\\jupyter\\lab\\staging\\node_modules\\node-pre-gyp\\lib\\install.js:118:27)
node-pre-gyp ERR! stack     at emitOne (events.js:101:20)
node-pre-gyp ERR! stack     at Request.emit (events.js:188:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (C:\\WinPython\\bd36\\buildQt5\\winpython-32bit-3.6.x.0\\python-3.6.4\\share\\jupyter\\lab\\staging\\node_modules\\node-pre-gyp\\node_modules\\request\\request.js:1074:10)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:188:7)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:363:20)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! System Windows_NT 10.0.16299
node-pre-gyp ERR! command \"C:\\\\WinPython\\\\bd36\\\\buildQt5\\\\winpython-32bit-3.6.x.0\\\\python-3.6.4\\\\..\\\\tools\\\\n\\\\node.exe\" \"C:\\\\WinPython\\\\bd36\\\\buildQt5\\\\winpython-32bit-3.6.x.0\\\\python-3.6.4\\\\share\\\\jupyter\\\\lab\\\\staging\\\\node_modules\\\\node-pre-gyp\\\\bin\\\\node-pre-gyp\" \"install\"
node-pre-gyp ERR! cwd C:\\WinPython\\bd36\\buildQt5\\winpython-32bit-3.6.x.0\\python-3.6.4\\share\\jupyter\\lab\\staging\\node_modules\\canvas-prebuilt
node-pre-gyp ERR! node -v v6.11.5
node-pre-gyp ERR! node-pre-gyp -v v0.6.39\n[-/4] ⠠ waiting...
[2/4] ⠠ canvas: gyp
[-/4] ⠐ waiting...
[-/4] ⠐ waiting...
warning Error running install script for optional dependency: "C:\\WinPython\\bd36\\buildQt5\\winpython-32bit-3.6.x.0\\python-3.6.4\\share\\jupyter\\lab\\staging\\node_modules\\canvas: Command failed.\nExit code: 1\nCommand: node-gyp rebuild\nArguments: \nDirectory: C:\\WinPython\\bd36\\buildQt5\\winpython-32bit-3.6.x.0\\python-3.6.4\\share\\jupyter\\lab\\staging\\node_modules\\canvas\nOutput:\nC:\\WinPython\\bd36\\buildQt5\\winpython-32bit-3.6.x.0\\python-3.6.4\\share\\jupyter\\lab\\staging\\node_modules\\canvas>if not defined npm_config_node_gyp (node \"C:\\WinPython\\bd36\\buildQt5\\winpython-32bit-3.6.x.0\\tools\\n\\node_modules\\npm\\bin\\node-gyp-bin\\\\..\\..\\node_modules\\node-gyp\\bin\\node-gyp.js\" rebuild )  else (node \"\" rebuild ) \r\ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.4.0\ngyp info using node@6.11.5 | win32 | ia32\ngyp http GET https://nodejs.org/download/release/v6.11.5/node-v6.11.5-headers.tar.gz\ngyp http 200 https://nodejs.org/download/release/v6.11.5/node-v6.11.5-headers.tar.gz\ngyp http GET https://nodejs.org/download/release/v6.11.5/SHASUMS256.txt\ngyp http GET https://nodejs.org/download/release/v6.11.5/win-x86/node.lib\ngyp http GET https://nodejs.org/download/release/v6.11.5/win-x64/node.lib\ngyp http 200 https://nodejs.org/download/release/v6.11.5/win-x64/node.lib\ngyp http 200 https://nodejs.org/download/release/v6.11.5/SHASUMS256.txt\ngyp http 200 https://nodejs.org/download/release/v6.11.5/win-x86/node.lib\ngyp info spawn C:\\WinPython\\basedir27\\buildZero\\winpython-32bit-2.7.x.2\\python-2.7.13\\python.exe\ngyp info spawn args [ 'C:\\\\WinPython\\\\bd36\\\\buildQt5\\\\winpython-32bit-3.6.x.0\\\\tools\\\\n\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\gyp\\\\gyp_main.py',\ngyp info spawn args   'binding.gyp',\ngyp info spawn args   '-f',\ngyp info spawn args   'msvs',\ngyp info spawn args   '-G',\ngyp info spawn args   'msvs_version=auto',\ngyp info spawn args   '-I',\ngyp info spawn args   'C:\\\\WinPython\\\\bd36\\\\buildQt5\\\\winpython-32bit-3.6.x.0\\\\python-3.6.4\\\\share\\\\jupyter\\\\lab\\\\staging\\\\node_modules\\\\canvas\\\\build\\\\config.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   'C:\\\\WinPython\\\\bd36\\\\buildQt5\\\\winpython-32bit-3.6.x.0\\\\tools\\\\n\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\addon.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   'C:\\\\WinPython\\\\bd36\\\\buildQt5\\\\winpython-32bit-3.6.x.0\\\\settings\\\\.node-gyp\\\\6.11.5\\\\include\\\\node\\\\common.gypi',\ngyp info spawn args   '-Dlibrary=shared_library',\ngyp info spawn args   '-Dvisibility=default',\ngyp info spawn args   '-Dnode_root_dir=C:\\\\WinPython\\\\bd36\\\\buildQt5\\\\winpython-32bit-3.6.x.0\\\\settings\\\\.node-gyp\\\\6.11.5',\ngyp info spawn args   '-Dnode_gyp_dir=C:\\\\WinPython\\\\bd36\\\\buildQt5\\\\winpython-32bit-3.6.x.0\\\\tools\\\\n\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp',\ngyp info spawn args   '-Dnode_lib_file=node.lib',\ngyp info spawn args   '-Dmodule_root_dir=C:\\\\WinPython\\\\bd36\\\\buildQt5\\\\winpython-32bit-3.6.x.0\\\\python-3.6.4\\\\share\\\\jupyter\\\\lab\\\\staging\\\\node_modules\\\\canvas',\ngyp info spawn args   '--depth=.',\ngyp info spawn args   '--no-parallel',\ngyp info spawn args   '--generator-output',\ngyp info spawn args   'C:\\\\WinPython\\\\bd36\\\\buildQt5\\\\winpython-32bit-3.6.x.0\\\\python-3.6.4\\\\share\\\\jupyter\\\\lab\\\\staging\\\\node_modules\\\\canvas\\\\build',\ngyp info spawn args   '-Goutput_dir=.' ]\nWarning: Missing input files:\r\nC:\\GTK\\bin\\zlib1.dll\r\nC:\\GTK\\bin\\libexpat-1.dll\r\nC:\\GTK\\bin\\libpng14-14.dll\r\nC:\\GTK\\bin\\libcairo-2.dll\r\nC:\\GTK\\bin\\libfontconfig-1.dll\r\nC:\\GTK\\bin\\libfreetype-6.dll\r\ngyp info spawn C:\\Program Files (x86)\\MSBuild\\14.0\\bin\\msbuild.exe\ngyp info spawn args [ 'build/binding.sln',\ngyp info spawn args   '/clp:Verbosity=minimal',\ngyp info spawn args   '/nologo',\ngyp info spawn args   '/p:Configuration=Release;Platform=Win32' ]\nG�n�ration des projets individuellement dans cette solution. Pour activer la g�n�ration en parall�le, ajoutez le commutateur \"/m\".\r\nMSBUILD : error MSB3428: Impossible de charger le composant Visual�C++ \"VCBuild.exe\". Pour corriger le probl�me, vous devez 1) installer le Kit de d�veloppement .NET Framework�2.0�SDK, 2) installer Microsoft Visual Studio�2005 ou 3) ajouter l'emplacement du composant au chemin d'acc�s syst�me, s'il est install� ailleurs.  [C:\\WinPython\\bd36\\buildQt5\\winpython-32bit-3.6.x.0\\python-3.6.4\\share\\jupyter\\lab\\staging\\node_modules\\canvas\\build\\binding.sln]\r\ngyp ERR! build error \ngyp ERR! stack Error: `C:\\Program Files (x86)\\MSBuild\\14.0\\bin\\msbuild.exe` failed with exit code: 1\ngyp ERR! stack     at ChildProcess.onExit (C:\\WinPython\\bd36\\buildQt5\\winpython-32bit-3.6.x.0\\tools\\n\\node_modules\\npm\\node_modules\\node-gyp\\lib\\build.js:276:23)\ngyp ERR! stack     at emitTwo (events.js:106:13)\ngyp ERR! stack     at ChildProcess.emit (events.js:191:7)\ngyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)\ngyp ERR! System Windows_NT 10.0.16299\ngyp ERR! command \"C:\\\\WinPython\\\\bd36\\\\buildQt5\\\\winpython-32bit-3.6.x.0\\\\python-3.6.4\\\\..\\\\tools\\\\n\\\\node.exe\" \"C:\\\\WinPython\\\\bd36\\\\buildQt5\\\\winpython-32bit-3.6.x.0\\\\tools\\\\n\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"rebuild\"\ngyp ERR! cwd C:\\WinPython\\bd36\\busuccess Saved lockfile.
Done in 590.91s.
> node C:\WinPython\bd36\buildQt5\winpython-32bit-3.6.x.0\python-3.6.4\lib\site-packages\jupyterlab\staging\yarn.js run build:prod
yarn run v1.3.2
$ webpack --config webpack.prod.config.js
````

js console errors
````

widgets.js:57 Uncaught TypeError: y.slider is not a function
    at Object.o [as init_slider] (widgets.js:57)
    at <anonymous>:25:11
    at t.attachWidget (panellayout.js:210)
    at t.insertWidget (panellayout.js:113)
    at t._insertOutput (widget.js:331)
    at t.onModelChanged (widget.js:242)
    at m (index.js:475)
    at Object.l [as emit] (index.js:433)
    at e.emit (index.js:106)
    at e._onListChanged (model.js:294)
2widgets.js:57 Uncaught TypeError: y.slider is not a function
    at Object.o [as init_slider] (widgets.js:57)
    at <anonymous>:25:11
    at t.attachWidget (panellayout.js:210)
    at t.insertWidget (panellayout.js:113)
    at t._insertOutput (widget.js:331)
    at t.onModelChanged (widget.js:242)
    at m (index.js:475)
    at Object.l [as emit] (index.js:433)
    at e.emit (index.js:106)
    at e._onListChanged (model.js:294)
o @ widgets.js:57
(anonymous) @ VM189:25
t.attachWidget @ panellayout.js:210
t.insertWidget @ panellayout.js:113
t._insertOutput @ widget.js:331
t.onModelChanged @ widget.js:242
m @ index.js:475
l @ index.js:433
e.emit @ index.js:106
e._onListChanged @ model.js:294
m @ index.js:475
l @ index.js:433
e.emit @ index.js:106
e.push @ observablelist.js:153
e._add @ model.js:230
e.add @ model.js:159
r._onIOPub @ widget.js:107
t._handleIOPub @ future.js:198
t.handleMsg @ future.js:171
_onWSMessage @ default.js:120
````

**Comment by stonebig** [comment]
retrying on notebook after lab failure, holoviews works, but everything looks curiously "doubled":
![holoju03](https://user-images.githubusercontent.com/4312421/36792263-61ba9f9e-1c9a-11e8-954d-88862b14a69a.PNG)

looks a jupyter at large issue

**Comment by stonebig** [comment]
will retry in a few days.

**Comment by philippjfr** [comment]
Thanks for trying again, I can't reproduce any of the issues you seem to be encountering and seemingly neither can @jlstevens. I'll try to get a few other people to try it.

**Comment by philippjfr** [comment]
>but everything looks curiously "doubled"

I actually remember encountering this before, but the issue always went away when I reloaded the page.

**Comment by ea42gh** [comment]
tried it too: worked for both matplotlib and bokeh.

**Comment by stonebig** [comment]
After a big rebuild + switch to nodejs-8/npm-5.6, it works. Awesome!

**Comment by stonebig** [comment]
and now it doesn't work again.... there is some hidden bad tricks in this javascript stack.

**Comment by philippjfr** [comment]
Your browser version would be very helpful.

**Comment by stonebig** [comment]
chrome 64.0.3282.186 (Build officiel) (64 bits)

**Comment by philippjfr** [comment]
Thanks, really hoped that'd be it, I've got a very similar build: ``Version 64.0.3282.167 (Official Build) (64-bit)``

**Comment by stonebig** [comment]
I think I read Jupyterlab tries to preserve a previous state of notebooks, so playing between mutiple versions, I may fall into some un-supported scenario.

**Comment by philippjfr** [comment]
What it could be is some other extension that adds a global jQuery.

**Comment by stonebig** [comment]
the yesterday 64 bit version still works.

**Comment by philippjfr** [comment]
Going to reopen as @stonebig is still reporting this issue, and I'm now able to reproduce it on http://pangeo.pydata.org/.

**Comment by stonebig** [comment]
did you make any progress on understanding what can cause this ?

**Comment by philippjfr** [comment]
Haven't had time to investigate yet unfortunately.

**Comment by philippjfr** [comment]
@stonebig Would you mind trying the latest version of the JupyterLab extension, as before you should be able to get it with:

```
jupyter labextension install @pyviz/jupyterlab_holoviews
```

**Comment by stonebig** [comment]
no need to do an uninstall ?

**Comment by philippjfr** [comment]
That's right, hope you don't mind but I still don't have a good way to reproduce it in an environment I can directly modify. If this doesn't work I may have to ask you again.

**Comment by stonebig** [comment]
well, no apparent effect:
![holoviews_jlab2](https://user-images.githubusercontent.com/4312421/37540149-465fbd60-2956-11e8-9ac3-d3bdc7cb8440.PNG)

**Comment by stonebig** [comment]
I see things, but not sure it's related:
````
widgets.js:61 Uncaught TypeError: x.slider is not a function
    at Object.i [as init_slider] (widgets.js:61)
    at <anonymous>:25:11
    at t.attachWidget (panellayout.js:210)
    at t.insertWidget (panellayout.js:113)
    at t._insertOutput (widget.js:331)
    at t.onModelChanged (widget.js:242)
    at m (index.js:475)
    at Object.l [as emit] (index.js:433)
    at e.emit (index.js:106)
    at e._onListChanged (model.js:300)
````

**Comment by philippjfr** [comment]
Damn, really hoped that would fix it. Could you try the JS console and seeing if ``HoloViews.jQuery.ui`` is defined?

**Comment by stonebig** [comment]
well, how do I see that ?

**Comment by philippjfr** [comment]
Don't think so, I think it's because jQuery.ui is not defined for whatever reason, but it would be great if you could confirm.

**Comment by stonebig** [comment]
didn't see it, just relaunching jlab to get a clearer view

**Comment by philippjfr** [comment]
>VM79:100 Jupyter notebooks comms not available. push_notebook() will not function. If running JupyterLab ensure the latest jupyterlab_bokeh extension is installed. In an exported notebook this warning is expected.
r @ VM79:100

That is expected.

**Comment by stonebig** [comment]
all list:
````
Bokeh: BokehJS plotting callback run at Fri Mar 16 2018 20:35:31 GMT+0100 (Paris, Madrid)
VM79:100 [bokeh] setting log level to: 'info'
VM79:376 Bokeh: injecting raw CSS
VM79:378 Bokeh: injecting raw CSS
VM79:380 Bokeh: injecting raw CSS
VM79:60 Bokeh: all callbacks have finished
VM79:100 Jupyter notebooks comms not available. push_notebook() will not function. If running JupyterLab ensure the latest jupyterlab_bokeh extension is installed. In an exported notebook this warning is expected.
r @ VM79:100
renderer.js:88 Kernel not found, could not connect to comm target  e91b55c1d6f641399f4e51fc73decc3f
VM79:100 [bokeh] document idle at 214 ms
renderer.js:81 Kernel not found, could not register comm target  8c44293ec2d54a7bb64116e281b4895d
index.js:78 Object
index.js:78 Object
3default.js:49 Starting WebSocket: ws://localhost:8888/api/kernels/da7c95ec-b4d3-4e22-ab87-6152cc06d54c
3default.js:1395 Kernel: connected (da7c95ec-b4d3-4e22-ab87-6152cc06d54c)
future.js:155 Uncaught (in promise) Error: Canceled
    at t.dispose (future.js:155)
    at default.js:385
    at Map.forEach (<anonymous>)
    at e.dispose (default.js:384)
    at e.dispose (default.js:244)
    at index.js:241
    at <anonymous>
index.js:186 Uncaught (in promise) TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at Object.t [as ensureMap] (index.js:186)
    at e.get (index.js:50)
    at t.isSelectedOrActive (widget.js:772)
    at actions.js:772
    at Object.i [as each] (iter.js:60)
    at Object.D [as clearOutputs] (actions.js:770)
    at Object.clearCurrent (index.js:1293)
    at index.js:415
    at e.execute (index.js:350)
2widgets.js:61 Uncaught TypeError: x.slider is not a function
    at Object.i [as init_slider] (widgets.js:61)
    at <anonymous>:25:11
    at t.attachWidget (panellayout.js:210)
    at t.insertWidget (panellayout.js:113)
    at t._insertOutput (widget.js:331)
    at t.onModelChanged (widget.js:242)
    at m (index.js:475)
    at Object.l [as emit] (index.js:433)
    at e.emit (index.js:106)
    at e._onListChanged (model.js:300)
i @ widgets.js:61
(anonymous) @ VM179:25
t.attachWidget @ panellayout.js:210
t.insertWidget @ panellayout.js:113
t._insertOutput @ widget.js:331
t.onModelChanged @ widget.js:242
m @ index.js:475
l @ index.js:433
e.emit @ index.js:106
e._onListChanged @ model.js:300
m @ index.js:475
l @ index.js:433
e.emit @ index.js:106
e.push @ observablelist.js:153
e._add @ model.js:230
e.add @ model.js:159
r._onIOPub @ widget.js:107
t._handleIOPub @ future.js:198
t.handleMsg @ future.js:171
_onWSMessage @ default.js:120
````

**Comment by philippjfr** [comment]
Could you try typing ``HoloViews.jQuery.ui`` in the console and see if that's defined?

**Comment by stonebig** [comment]
````
HoloViews.jQuery.ui
undefined
````

**Comment by stonebig** [comment]
````
!jupyter labextension list
JupyterLab v0.31.12
Known labextensions:
   app dir: C:\WinP\bd36\buQt5\winp64-3.6.x.0\python-3.6.4.amd64\share\jupyter\lab
@jupyter-widgets/jupyterlab-manager
        @jupyter-widgets/jupyterlab-manager v0.33.2 enabled  ok
@jupyterlab/vega3-extension
        @jupyterlab/vega3-extension v0.14.4 enabled  ok
@pyviz/jupyterlab_holoviews
        @pyviz/jupyterlab_holoviews v0.2.2 enabled  ok
bqplot
        bqplot v0.3.6 enabled  ok
jupyter-leaflet
        jupyter-leaflet v0.7.1 enabled  ok
jupyter-matplotlib
        jupyter-matplotlib v0.3.0 enabled  ok
jupyter-threejs
        jupyter-threejs v0.4.1 enabled  ok
jupyterlab-datawidgets
        jupyterlab-datawidgets v5.0.1 enabled  ok
jupyterlab_bokeh
        jupyterlab_bokeh v0.4.0 enabled  ok
````

**Comment by philippjfr** [comment]
Okay, great thanks, no clue why that's the case on your system but not mine but at least that's a hint.

**Comment by philippjfr** [comment]
That's list of extensions is helpful too in case they are somehow interfering with each other.

**Comment by stonebig** [comment]
trying on "edge"... same result. welll, that will be all for today for me. thanks for having tried to resolve this .

**Comment by philippjfr** [comment]
Thanks a lot for trying. Hopefully I can somehow put together an environment to reproduce it for myself.

**Comment by philippjfr** [comment]
Great news, after updating to bleeding edge JupyterLab I can now reproduce the issue.

**Comment by philippjfr** [comment]
Damn, spoke too soon, it still works fine after rebuilding all the extensions. Never have I wanted something not to work more!

**Comment by ea42gh** [comment]
You had to rebuild the extensions? Might that be the issue @stonebig is facing?

**Comment by philippjfr** [comment]
Not sure what you mean all extensions are rebuilt whenever you install a labextension.

**Comment by ea42gh** [comment]
I was wondering how you got into an inconsistent state

**Comment by philippjfr** [comment]
Installing a new version of JLab temporarily uninstalls existing extensions.

**Comment by philippjfr** [comment]
@stonebig Okay, if you're not sick of it by now, could you have another go? I've now replaced the jquery-ui dependency with noUISlider in @pyviz/jupyterlab_holoviews 0.3.0, along with some CSS fixes in https://github.com/ioam/holoviews/pull/2456.

**Comment by bltpyro** [comment]
I'll just comment that I'm having the same problem. Standard notebook works fine, but I'm seeing the same thing as him (no graphs,  I updated jupyterlab and the extension and did the rebuild, but it still happens with the same block of code being used here. 

Chrome 65.0.3325.181 (Official Build) (64-bit)
Python 3.6
holoviews 1.9.4
Jupyter notebook version 5.4.1
Jupyter lab version 0.31.12
matplotlib                2.1.1
bokeh                     0.12.14

Known labextensions:
   app dir: C:\Users\btaylor\AppData\Local\Continuum\Anaconda3\share\jupyter\lab
@jupyterlab/plotly-extension
        @jupyterlab/plotly-extension v0.14.4 enabled  ok
@pyviz/jupyterlab_holoviews
        @pyviz/jupyterlab_holoviews v0.3.2 enabled  ok
jupyter-matplotlib
        jupyter-matplotlib v0.3.0 enabled  ok
jupyterlab_bokeh
        jupyterlab_bokeh v0.4.0 enabled  ok

HoloViews.jQuery.ui 
    Uncaught ReferenceError: HoloViews is not defined at <anonymous>:1:1

When running the cell it says:
   JupyterLab does not execute inline JavaScript in HTML output

At the very top of the console it says 
    Plugin 'matplotlib-jupyter:main' failed to activate.
    Error: No provider for: jupyter.extensions.jupyterWidgetRegistry.

I tried with bokeh backend and get the same result. 

I'm happy to try anything you can think of.

**Comment by philippjfr** [comment]
@bltpyro Different issue, you'll have to get holoviews master and bokeh master to get things working. I'm fairly confident the issue is now resolved with those versions.

**Comment by stonebig** [comment]
trying today ...

**Comment by crlag** [comment]
Hi, I am having the same issue with jupyterlab as @stonebig. I've installed all the extensions, but still no luck with the bokeh. However, it works with the matplolib extension. 
<img width="1440" alt="holoviews" src="https://user-images.githubusercontent.com/8115916/37867584-332830ce-2f9b-11e8-96e5-19093ed79e82.png">

**Comment by philippjfr** [comment]
@crlag Could you check which versions of holoviews, bokeh and jupyterlab_bokeh you have and report those here? Currently this is required:

```
conda install -c bokeh/label/dev bokeh
conda install -c ioam/label/dev holoviews
jupyter labextension install @pyviz/jupyterlab_holoviews
```

One you've done that you should have bokeh 0.12.15devX, holoviews 1.10.0a2 and jupyterlab_holoviews 0.3.2.

**Comment by crlag** [comment]
@philippjfr that was the problem... now its working. Thank you!

**Comment by stonebig** [comment]
it works !

**Comment by philippjfr** [comment]
Thanks for being our guinea pig and for following up multiple times!

**Comment by stonebig** [comment]
Thanks for having taken care of my not-your-mainstream use-case.

**Comment by arokem** [comment]
This same issue is currently solved for me by adding: 

    jupyter labextension install @pyviz/jupyterlab_pyviz

to my installation process (the process mentioned in https://github.com/pyviz/holoviews/issues/2379#issuecomment-375916214 is now outdated)
