### ISSUE TITLE
Histogram with logy=True not displaying with Bokeh

### ISSUE THREAD

**Issue by rappdw** [ioam/holoviews#2591]
Trying to plot a histogram using Bokeh backend and log scale y axis results in a blank plot.

Using either matplotlib backend or removing the log scale allows the data to plot.

![bokeh_linear_scale](https://user-images.githubusercontent.com/210863/39073127-f8676b84-44a9-11e8-942d-0115fb7c4eea.png)
![matplotlib_log_scale_bokeh_log_scale](https://user-images.githubusercontent.com/210863/39073137-05623daa-44aa-11e8-9d36-211a327d1aa1.png)

I've zipped and attached a notebook to demonstrate the problem (as well as including screenshots of the cases enumerated in the notebook)

[Notebook.zip](https://github.com/ioam/holoviews/files/1933620/BugReport.zip)

**Comment by jlstevens** [comment]
Depending on how tricky this is to address, it might be something worth fixing for 1.10.2...

**Comment by hyamanieu** [comment]
I would like to pop up this issue. I don't see any warning or bugs in either the notebook or the browser console.

**Comment by fmfreeze** [comment]
I thought this should have been fixed generally by (already closed) issue  [#1679](https://github.com/holoviz/holoviews/issues/1679) and its pull request [#1691](https://github.com/holoviz/holoviews/pull/1691) by @philippjfr.

But for histograms it doesn't work although I get at least the Warning 
`WARNING:param.HistogramPlot05545: Logarithmic axis range encountered value less than or equal to zero, please supply explicit lower-bound to override default of 0.110.`

**Comment by nitrocalcite** [comment]
For future reference, this looks like it's caused by bokeh/bokeh#9105 and progress on fixing it is being tracked at bokeh/bokeh#6536

**Comment by michaelc12qe** [comment]
This bug still exists in holoviews 1.18.3. Reproduced using:

```
hv.Curve(
    (np.logspace(0,10, num=100), np.logspace(-16, -16,num=100))
).opts(
    logx=True,
    logy=True,
)
```

**Comment by ampilnick** [comment]
Please don't close this issue until it will not fixed!
Now **hvplot.hist(..., logy=True)** is still broken.

**Comment by maximlt** [comment]
Hi @ampilnick, this issue is not closed.

**Comment by ampilnick** [comment]
Oops... yes - I realized)
Thanks!

**Comment by G-Guillard** [comment]
Still happening in 1.20.2.  Any workaround ?

**Comment by G-Guillard** [comment]
> For future reference, this looks like it's caused by [bokeh/bokeh#9105](https://github.com/bokeh/bokeh/issues/9105) and progress on fixing it is being tracked at [bokeh/bokeh#6536](https://github.com/bokeh/bokeh/issues/6536)

Are you sure ?  This issue doesn’t particularly seem related to 0 values, try

> hv.Histogram(np.histogram(range(100), 100)).opts(xlim=(20,80), logy=True)

It has no empty or 0 bin, 20 bins before and 20 bins after, and it still fails to display…

**Comment by michaelaye** [comment]
it is interesting, that 

    pd.Series(range(100)).hvplot.hist(logy=True)

fails, despite there being no 0-entry holes, and again, matplotlib has no issue with that:

    pd.Series(range(100)).plot.hist(log=True)

IMHO, this should have been wrapped by holoviews years ago, and I'm convinced that user-unfriendlyness like this (how ever much the error is mathematically correct) has cost holoviews uptake in the data science community. This needs to be fixed ASAP, one way or another.

**Comment by michaelaye** [comment]
Hallelujah!! Thanks much, @hoxbro !

**Comment by MikeB2019x** [comment]
Agree with @michaelaye, very much appreciated!
